# Generated by Django 5.2.7 on 2025-10-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('bot_id', models.CharField(max_length=100)),
                ('index_id', models.CharField(max_length=100, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pinecone_namespace', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
